language: java
install: true
script:
- make
deploy:
  provider: releases
  api-key:
    secure: Spyxj45UoTcALwTn6+wM6ZYRwXfFxFimfb2HU2FfmAE3Z/baTf1IBsvcF5mq9Jbiq22v6b17kr6wcqehH2S6JWdC2Vrhu/Y0wh1Zy7kpYj0FLDVoMZL0foLw5ShFBGg3c8FN7gmCbwlr3mdlY+3OFRvfQPwUd6WE+ebk0rBzZ9gQDk1yl/UZH1MK01JX98w0SyBbDJ+AHNrAKpk/8ZXh+Q8e1+8EUdlb5QCxAAtj8PPRUdLa34BK9cRFztBpiH2/J7GcEyIRfGju+xuwxyfnNTRgKRaZomxqE2OroQIwpyDCyr1AmEDOWtSiu4gEa4OW7nKeq3w9fNtQa0HFxOkdy+79CgISgdE3hQoBSB8un3KVpSrPuI/llM9A2y9GtSJn46it6uUCOmldXuPSiR2YrG4x+4G5EGsTE0Ci0Im+j+k1MmAopclOp64BzwE4K5P2lgv0qS9+Llg9pvCdyapMtqiOb6vd95VLCzhmbOiChiQj9QK4q3OEOwZHxNOi5oUUTSxp7Azf/3fHaOqSCSQ25UrI9JoBMDrX5sTTbSWToxKnFVc6k7OOYYbX4RPJ5MsCEkUo5Rvz4QAOXnGppVobTPYNSo2fOO0TBZPOCasyTy4QtLrU/gOJo1cBxe4nHm0DfNg+gn2B+1RkjNqBESq7tXx31g+CLBQQYKP+IE68/Ag=
  file_glob: true
  file: release/*
  skip_cleanup: true
  on:
    tags: true
